### ISSUE TITLE
`Element: Numeric` requirement

### ISSUE THREAD

**Issue by agurtovoy** [Galarius/ring-buffer#2]
Hi there,

This library would fit our needs perfectly if not for the requirement for `Element` to conform to the `Numeric` protocol; wondering if this requirement is essential or accidental, and if the latter, if it can be removed.

Thanks so much!

**Comment by Galarius** [comment]
Hi! I removed the `Numeric` constraint in [bc17d18](https://github.com/Galarius/ring-buffer/commit/bc17d189b8f61654160af984d00426bc39bada8e).

**Comment by agurtovoy** [comment]
Thanks for the quick fix!
